### ISSUE TITLE
Tracking issue for 2.0.0

### ISSUE THREAD

**Issue by lestrrat** [lestrrat-go/jwx#388]
When ready, merge [next-major-release branch](/lestrrat-go/jwx/tree/v2)

~~For those of you reading this: No, there's no plan for a 2.0.0 yet. Once we have enough breaking changes, we'll think about when to release v2. The items in this issue are currently either low-priority, or require enough changes that it would have significant impact on the users.~~

These are major items for 2.0.0

* [x] ~~#385 [jws] Change jws.VerifySet to return the key used to verify the payload~~ This has been implemented via `jws.KeyUsed` instead of a return value
* [x] #370 Replace github.com/pkg/errors with native error wrapping
* [ ] ~~Rename `jwt.WithVerify` to something like `jwt.WithVerifyKey`~~
* [ ] ~~Remove `jwt.WithJwsHeaders`, and just allow passing `jws.SignOption` to `jwt.Sign`~~
* [ ] ~~Rethink `jws.Sign` so that it flows better with detached payload?~~
* [x] #553 Create `jwa.KeyAlgorithm` so `(jwk.Key).Algorithm()` can return either jwa.SignatureAlgorithm or jwa.KeyAlgorithm? 
* [x] #577
* [x] #579
* [x] #582
* [x] #590
* [x] #641
* [x] #647 
* [x] #648
* [x] #654

**Comment by lestrrat** [comment]
Closing this as I release an alpha version today
